services:
  # PostgreSQL for Rails app logic
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: flexlink_config
      POSTGRES_USER: flexlink_user
      POSTGRES_PASSWORD: flexlink_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U flexlink_user -d flexlink_config" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and background jobs
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rails application
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/tmp
    working_dir: /app
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://flexlink_user:flexlink_password@postgres:5432/flexlink_config
      - REDIS_URL=redis://redis:6379/0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        bundle install &&
        bundle exec rails db:create db:migrate &&
        bundle exec guard &
        bundle exec rails server -b 0.0.0.0 -p 3000
      "

  # Background job processor
  sidekiq:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://flexlink_user:flexlink_password@postgres:5432/flexlink_config
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        bundle install &&
        bundle exec sidekiq
      "

volumes:
  postgres_data:
  redis_data:
