services:
  - type: web
    name: flexlink-guided-configurator
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: flexlink-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: flexlink-redis
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
  - type: redis
    name: flexlink-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: flexlink-postgres
    databaseName: flexlink_production
    user: flexlink_user
    plan: free 