default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: flexlink_config_development
  username: flexlink_user
  password: flexlink_password
  host: postgres
  port: 5432

test:
  <<: *default
  database: flexlink_config_test
  username: flexlink_user
  password: flexlink_password
  host: postgres
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> 