default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://flexlink_user:flexlink_password@localhost:5432/flexlink_config' %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://flexlink_user:flexlink_password@localhost:5432/flexlink_config_test' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> 